### ISSUE TITLE
NoneType object Error when generating

### ISSUE THREAD

**Issue by sinhzun** [amirbar/rnn.wgan#9]
Hi, I'm interested in your RNN-GANs model but I'm still new to this domain. I'm trying to run your code but I get some problems. 
The first one is when I run the generating command: 
`python generate.py --CKPT_PATH=/logs/Generator_RNN_CL_VL_TH-Discriminator_RNN-50-10-512-512-1509799522.05-/checkpoint --DISC_GRU_LAYERS=2 --GEN_GRU_LAYERS=2`
The system outputs this error: 
```
File "generate.py", line 20, in <module>
    _, inference_op = Generator(BATCH_SIZE, charmap_len, seq_len=SEQ_LEN)
  File "/.../rnn.wgan/model.py", line 51, in Generator_RNN_CL_VL_TH
    cells.append(rnn_cell(num_neurons))
TypeError: 'NoneType' object is not callable
```

The second one is when I train the model by running: `python curriculum_training.py`. It takes a lot of time, 3 days for training seq-1 to seq-4. I run this code on a server with 256CPU , 1536Core, Intel Xeon E5-4655v3 [6Core, 30M Cache, 2.9GHz], 32TB of RAM (DDR4).

Can you help me about that? Thank you in advance.

**Comment by ofirpress** [comment]
1) About the NoneType bug- are you sure you are using the correct version of TF? This repository may not work with other versions of TF.
2) As with all neural networks, this model trains much faster on GPU than on CPU. If you don't have a GPU it will take a long time to train the network.

If you have further questions you can email me.

**Comment by sinhzun** [comment]
Dear Ofir,

My Tensorflow version is 1.1 as your code required. I also tried on other version of TF (with a little modification) but it still got the same error.
About the second problem, I will try training on GPU later. Thank you.

**Comment by ofirpress** [comment]
I'm not exactly sure why you are receiving this error but I think it could be because your checkpoint directory is incorrect.
Maybe it should be:
python generate.py --CKPT_PATH=**.**/logs/Generator_RNN_CL_VL_TH-Discriminator_RNN-50-10-512-512-1509799522.05-/checkpoint --DISC_GRU_LAYERS=2 --GEN_GRU_LAYERS=2

(Notice the period I put at the beginning of the directory)

**Comment by sinhzun** [comment]
I tried that path but it still got the same error @@.

**Comment by sinhzun** [comment]
Ofir, in your code, file generate.py, lines 20:
`_, inference_op = Generator(BATCH_SIZE, charmap_len, seq_len=SEQ_LEN)`
You just initialize the Generator with 3 first parameter, so the rnn_cell parameter is still None, is that okay?

**Comment by ofirpress** [comment]
Yup the code is fine.

Make sure that this directory actually exists
./logs/Generator_RNN_CL_VL_TH-Discriminator_RNN-50-10-512-512-1509799522.05-/checkpoint 

I think that the problem is that the directory you gave the program is wrong.

**Comment by fupolarbear** [comment]
same issue in #10 . I'm also not familiar with the code, but after some code reading, I found maybe the problem is in [the line L20](https://github.com/amirbar/rnn.wgan/blob/master/generate.py#L20) of generate.py, where you should pass the correct parameter `rnn_cell` to the function call:
`_, inference_op = Generator(BATCH_SIZE, charmap_len, seq_len=SEQ_LEN, rnn_cell=RNN_CELL)
disc_fake = Discriminator(inference_op, charmap_len, SEQ_LEN, reuse=False, rnn_cell=RNN_CELL)`

But this single fix won't let the code work. After some fail and trial, I found [the line L238](https://github.com/amirbar/rnn.wgan/blob/master/single_length_train.py#L138) in single_length_train.py has changed the ckp data path by arbitrarily adding a `/ckp` suffix, which breaks the readme guide.
so, instead of using path like:
--CKPT_PATH=./logs/Generator_RNN_CL_VL_TH-Discriminator_RNN-50-10-512-512-1516543503.49-/checkpoint
you should type something like:
--CKPT_PATH=./logs/Generator_RNN_CL_VL_TH-Discriminator_RNN-50-10-512-512-1516543503.49-/checkpoint/seq-5/ckp

I'm so sorry to point out that maybe the merge from NickShahML breaks some code, which the authors may not intend to? :)

**Comment by ofirpress** [comment]
Thanks for reporting this. We've reverted the code back to what it was when we published the paper. We believe this issue should be solved, as that code was thoroughly tested by us.

If this issue persists, please post here.
